export const siteMetadata = {
  title: 'Fahmin Guliyev',
  author: 'Fahmin Guliyev',
  headerTitle: 'fahminguliyev',
  description: 'Software Developer',
  language: 'en-us',
  theme: 'dark', // system, dark or light
  siteUrl: 'https://fahminguliyev.com',
  siteRepo: 'https://github.com/faxmishok/fahminguliyev',
  siteLogoDark: '/static/images/logo-white.svg',
  siteLogoLight: '/static/images/logo-black.svg',
  image: '/static/images/avatar.webp',
  socialBanner: '/static/images/twitter-card.png',
  email: 'fahminguliyev6@gmail.com',
  github: 'https://github.com/faxmishok',
  twitter: 'https://x.com/notchwonders',
  facebook: 'https://facebook.com/faxmishok',
  linkedin: 'https://www.linkedin.com/in/fahmin/',
  spotify: 'https://open.spotify.com/user/31m3q773ylz64ws5qfpfvplprb34',
  steam: 'https://steamcommunity.com/id/faxmishok/',
  locale: 'en-US',
};
